var data = {
              "id": "Model 1",
              "id": "1",
              "genes": [],
              "metabolites": [{
                                "id": "a",
                                "name": "A",
                                "species": "Ecoli",
                                "compartment": "e",
                                "notes": {},
                                "_constraint_sense": "E",
                                "charge": -2,
                                "_bound": 0,
                                "formula": "aaa",
                                "annotation": {}
                              },
                             {
                                "id": "b",
                                "name": "B",
                                "species": "Ecoli",
                                "compartment": "e",
                                "notes": {},
                                "_constraint_sense": "E",
                                "charge": -2,
                                "_bound": 0,
                                "formula": "bbb",
                                "annotation": {}
                              },
                             {
                                "id": "c",
                                "name": "C",
                                "species": "Ecoli",
                                "compartment": "e",
                                "notes": {},
                                "_constraint_sense": "E",
                                "charge": -2,
                                "_bound": 0,
                                "formula": "ccc",
                                "annotation": {}
                              },
                             {
                                "id": "d",
                                "name": "D",
                                "species": "Ecoli",
                                "compartment": "e",
                                "notes": {},
                                "_constraint_sense": "E",
                                "charge": -2,
                                "_bound": 0,
                                "formula": "ddd",
                                "annotation": {}
                              },{
                                "id": "e",
                                "name": "E",
                                "species": "Ecoli",
                                "compartment": "c",
                                "notes": {},
                                "_constraint_sense": "E",
                                "charge": -2,
                                "_bound": 0,
                                "formula": "eee",
                                "annotation": {}
                              },
                             {
                                "id": "f",
                                "name": "F",
                                "species": "Ecoli",
                                "compartment": "c",
                                "notes": {},
                                "_constraint_sense": "E",
                                "charge": -2,
                                "_bound": 0,
                                "formula": "fff",
                                "annotation": {}
                              },{
                                "id": "g",
                                "name": "G",
                                "species": "Ecoli",
                                "compartment": "c",
                                "notes": {},
                                "_constraint_sense": "E",
                                "charge": -2,
                                "_bound": 0,
                                "formula": "ggg",
                                "annotation": {}
                              },
                             {
                                "id": "h",
                                "name": "H",
                                "species": "Ecoli",
                                "compartment": "c",
                                "notes": {},
                                "_constraint_sense": "E",
                                "charge": -2,
                                "_bound": 0,
                                "formula": "hhh",
                                "annotation": {}
                              },
                             {
                                "id": "i",
                                "name": "I",
                                "species": "Ecoli",
                                "compartment": "c",
                                "notes": {},
                                "_constraint_sense": "E",
                                "charge": -2,
                                "_bound": 0,
                                "formula": "iii",
                                "annotation": {}
                              }],
              "notes": [],
              "reactions": [{
                              "id": "v1",
                              "metabolites": {"h": -1,"a": 1},
                              "name": "h -> a",
                              "upper_bound": 1000,
                              "notes": {},
                              "subsystem": "",
                              "variable_kind": "countinuous",
                              "lower_bound": 0,
                              "gene_reaction_rule": "",
                              "objective_coefficient":0
                            },
                           {
                              "id": "v2",
                              "metabolites": {"g": -1, "b": 1},
                              "name": "g -> b",
                              "upper_bound": 1000,
                              "notes": {},
                              "subsystem": "",
                              "variable_kind": "countinuous",
                              "lower_bound": 0,
                              "gene_reaction_rule": "",
                              "objective_coefficient":0
                            },
                           {
                              "id": "v3",
                              "metabolites": {"c": -1, "i": 1},
                              "name": "c -> i",
                              "upper_bound": 1000,
                              "notes": {},
                              "subsystem": "",
                              "variable_kind": "countinuous",
                              "lower_bound": 0,
                              "gene_reaction_rule": "",
                              "objective_coefficient":0
                            },
                           {
                              "id": "v4",
                              "metabolites": {"d": -1, "c": 1},
                              "name": "d -> c",
                              "upper_bound": 1000,
                              "notes": {},
                              "subsystem": "",
                              "variable_kind": "countinuous",
                              "lower_bound": 0,
                              "gene_reaction_rule": "",
                              "objective_coefficient":0
                            },
                           {
                              "id": "v5",
                              "metabolites": {"e": -1, "f": 1},
                              "name": "e -> f",
                              "upper_bound": 1000,
                              "notes": {},
                              "subsystem": "",
                              "variable_kind": "countinuous",
                              "lower_bound": 0,
                              "gene_reaction_rule": "",
                              "objective_coefficient":0
                            }]
           };
